### ISSUE TITLE
crash with forigified fabric api with a renderer probably from crackers wither storm modand embeddium (1.20.1)

### ISSUE THREAD

**Issue by loti1234** [Sinytra/ForgifiedFabricAPI#82] opened 2023-11-21 06:16 UTC
### Describe the bug

crash when mining wither skull

### Steps to reproduce

1. go to survival
2. try to break wither skull
3. 
...

### Logs

https://gist.github.com/loti1234/5cfe11326391b8b2271824b56fedd06b

**Comment by Su5eD** [comment] 2023-11-21 13:50
Duplicate of #81

**Closed as not planned by Su5eD** 2023-11-21 13:50 UTC
Labels: duplicate
