### ISSUE TITLE
Enchancement

### ISSUE THREAD

**Issue by Nol-inuse** [Sinytra/ForgifiedFabricAPI#84] opened 2023-11-28 18:19 UTC
### Describe the bug

crashes on startup

### Steps to reproduce

1. Install enchantment and tooltipfix
2. try to load the game 
3. c r a s h
...

### Additional context

uh enchancement is cool :thumbsup:

**Comment by Su5eD** [comment] 2023-11-28 19:06
Duplicate of Sinytra/Connector#297

**Closed as not planned by Su5eD** 2023-11-28 19:06 UTC
Labels: bug
