### ISSUE TITLE
Tech Reborn Crashing if scrolling in EMI

### ISSUE THREAD

**Issue by MSandro** [Sinytra/ForgifiedFabricAPI#54] opened 2023-09-20 18:48 UTC
### Describe the bug

if I scroll to techReborn in EMI it crashes

### Steps to reproduce

1. install MC with Connector and Forgified
2. install TechReborn and EMI
3. load up a world
4. scroll in EMI
5. crash

### Logs

https://gist.github.com/MSandro/8ad7acd2a9517e2a628ed679737ec612

**Comment by Su5eD** [comment] 2023-09-23 08:34
I'm not able to reproduce this issue with only the following installed:
- Forge 47.1.3
- TechReborn 5.8.7
- Forgified Fabric API 0.88.1+1.9.15+1.20.1
- emi 1.0.19+1.20.1+forge
- ConnectorExtras 1.1.0+1.20.1
- Connector 1.0.0-beta.15+1.20.1-full

**Comment by Su5eD** [comment] 2023-09-27 19:41
Fixed in 4ac5e37ae1186f201ea93cfdc13e227b333cd6fa

**Closed as completed by Su5eD** 2023-09-27 19:41 UTC
Labels: bug
