### ISSUE TITLE
The mod don't work with the oldest version of Forge.

### ISSUE THREAD

**Issue by wycats0** [Sinytra/ForgifiedFabricAPI#45] opened 2023-09-13 02:44 UTC
### Describe the bug

When I start the game with my modpack, the game crashes; when I start the game only with Forgified Fabric Api and Sinytra Connector, the game asks that I use Forge 47.1.3.

### Steps to reproduce

1. Start the game with a Sinytra Connector, Forgified Fabric Api and Forge 47.1.47.
[crash-2023-09-12_23.43.05-client.txt](https://github.com/Sinytra/ForgifiedFabricAPI/files/12592857/crash-2023-09-12_23.43.05-client.txt)

### Logs

https://mclo.gs/37DnEN8

**Comment by SuperStormer** [comment] 2023-09-13 04:52
#15

**Comment by Su5eD** [comment] 2023-09-13 14:38
Duplicate of #15

**Closed as not planned by Su5eD** 2023-09-13 14:37 UTC
Labels: bug
