### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by dabomb6405** [Sinytra/ForgifiedFabricAPI#27] opened 2023-08-22 22:05 UTC
### Describe the bug

When I try and load the game, it loads for a few seconds and then immediately crashes

### Steps to reproduce

1. Start game
2. Wait a few seconds
3. Crash :(
...

### Logs

https://pastebin.com/xSATcqwh

### Additional context

Modlist is here:
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/66895105/22ae8d23-36d0-423f-9578-c1b64a011f51)
Also important to note I am using Forge 1.20.1 47.1.3.

**Comment by Su5eD** [comment] 2023-08-22 22:22
The provided log does not contain errors nor crash logs. Please upload your debug.log using a paste site.

**Comment by dabomb6405** [comment] 2023-08-23 04:54
Here's a debug log: https://pastebin.com/AUZFaPcK

**Comment by BL4NK1E** [comment] 2023-08-23 19:50
have the same problem just cant make it work

**Comment by Su5eD** [comment] 2023-08-25 17:28
Have you been able to figure out which mod is causing the crash? Unfortunately, the debug.log doesn't have any useful information either.

**Comment by SaltSouls** [comment] 2023-08-28 21:30
I can say without a shadow of a doubt that it is supplementaries. When removing the mod, the game is able to boot up just fine. Though I'm not sure if it is the way that moonlight lib and supp are interacting, or if it is just supp doing something strange that is causing the crash.

EDIT: Yeah, it seems to be an issue with Moonlight Library. Even after removing supp, I'm still consistently getting a crashes caused by Moonlight. It isn't a hard crash like with supp, but it still won't let me load into a world.
Can confirm that after removing Moonlight and all mods that use it, I can load into the world.

**Comment by Su5eD** [comment] 2023-09-03 12:58
I tried running supplementaries and moonlight lib with FFAPI, but it all works fine for me. Do you have a log perhaps?

**Comment by JanikDerProfi** [comment] 2023-09-03 15:51
i have the same problem, i tried later versions of the mods but it still wont work

**Comment by Su5eD** [comment] 2023-09-04 10:40
@JanikDerProfi and what mods are you using? Is it just FFAPI, Moonlightlib and Supplementaries?

**Comment by Starexify** [comment] 2023-09-04 14:36
Moonlightlib doesnt crash with the mod, try removing CreativeCore.

**Comment by Meganium97** [comment] 2023-09-09 00:39
I'm getting the same issue, and I have mostly the same mods.
https://pastebin.com/eqgX3i5m

**Comment by Su5eD** [comment] 2023-09-09 07:51
That's the same crash as in #22

**Comment by Zombie287432874** [comment] 2023-09-17 06:12
I'm getting the same issue
![Me too](https://github.com/Sinytra/ForgifiedFabricAPI/assets/137406732/75fa6a5c-856a-4158-8811-b7f2e6e10563)

**Comment by Starexify** [comment] 2023-09-17 08:09
> I'm getting the same issue
> ![Me too](https://github.com/Sinytra/ForgifiedFabricAPI/assets/137406732/75fa6a5c-856a-4158-8811-b7f2e6e10563)
> 

I dont think lazydfu works...

**Comment by Su5eD** [comment] 2023-09-23 09:20
I'll be closing this as not enough details have been provided to reproduce the issue. When submitting issues, please make sure to provide a minimal list of mods that are required to reproduce the issue, rather than listing all mods you have installed, as that makes tracking down the issue difficult.

**Closed as not planned by Su5eD** 2023-09-23 09:20 UTC
Labels: bug, invalid
