### ISSUE TITLE
Crash: Mixin Transformer Error - Forge 47.2.0 exclusive

### ISSUE THREAD

**Issue by JaceTheGrayOne** [Sinytra/ForgifiedFabricAPI#83] opened 2023-11-23 17:10 UTC
### Describe the bug

Injection fault from redirector method "redirectGetFacing" in the "OverlayVertexConsumer" mixin when interacting with any destructible block.

### Steps to reproduce

1. Install Forge 47.2.0 with Forgified Fabric API + Connector
2. Load into game
3. Punch tree

### Logs

https://pastebin.com/8M3q7fhL

### Additional context

Forge 47.2.0
Forgified Fabric API 0.90.7+1.10.0+1.20.1
Connector 1.0.0-beta.25+1.20.1

This does not occur on Forge 47.1.3 and downgrading from 47.2.0 to 47.1.3 without making any other changes resolves this issue. Unfortunately mods like Better Combat require FFAPI+Connector and Forge 47.2.0.

Modlist below. I understand it is a large number of mods but this was happening with just FFAPI/Connector/DoABarrelRoll installed. I just downgraded to Forge 47.1.3 to fix it and it wasn't a problem until I decided to add Better Combat to the list just now.

[Current Modlist] 
.connector
Ambient Environment
AmbientSounds
Architectury
AttributeFix
Better Advancements
Better Animations Collection
Better Mods Button
Better Third Person
BetterBurning
BetterF3
betterfpsdist mod
biomemusic mod
Caelus API
Canary
Catalogue
Cloth Config v10 API
Clumps
Controlling
CreativeCore
Cupboard utilities
Curios API
Do a Barrel Roll
Dragon Mounts: Legacy
Embeddium
Embeddium++
Expanded Combat
Falling Leaves
Fancy Dyes
Farsight mod
Ferrite Core
Forge Config Screens
Forgified Fabric API
GeckoLib 4
Get It Together, Drops!
Iron's Spells 'n Spellbooks
Just Enough Items
Kotlin for Forge
MaxHealthFix
medievalmusic mod
MidnightLib
ModernFix
Mouse Tweaks
NotEnoughAnimations Mod
Panda's Extra Details
Panda's Falling Trees
ParCool!
Patchouli
Player Animator
Iron's Spells 'n Spellbooks
Just Enough Items
Kotlin for Forge
MaxHealthFix
medievalmusic mod
MidnightLib
ModernFix
Mouse Tweaks
NotEnoughAnimations Mod
Panda's Extra Details
Panda's Falling Trees
ParCool!
Patchouli
Player Animator
Projectile Damage Attribute
Puzzles Lib
Resourceify
Rubidium Dynamic Lights
Searchables
Sinytra Connector
Sound Physics Remastered
spark
TexTrue's Embeddium Options
YetAnotherConfigLib

**Comment by Su5eD** [comment] 2023-11-23 18:39
Duplicate of #81, was fixed in version [0.90.7+1.10.1+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.90.7+1.10.1+1.20.1)

**Closed as not planned by Su5eD** 2023-11-23 18:39 UTC
Labels: duplicate
