### ISSUE TITLE
Optifine compatibility 

### ISSUE THREAD

**Issue by Arch23-tech** [Sinytra/ForgifiedFabricAPI#131] opened 2024-06-24 21:24 UTC
### Describe the bug

Plz if this mod could reach a state being compatible with optifine and not causing crashes.

### Steps to reproduce

1.
2.
3.
...

**Comment by Su5eD** [comment] 2024-06-24 21:32
Duplicate of #41. Please read our [FAQ](https://sinytra.org/docs/connector/faq) for more information

**Closed as not planned by Su5eD** 2024-06-24 21:32 UTC
Labels: duplicate, wontfix
